[package]
name = "dev_kkblparker_minecraftworkshop"
description = "Adds an in-panel Workshop browser for Minecraft plugins and mods, backed by the Modrinth API."
authors = ["kkblparker"]
version = "1.0.0"
edition = { workspace = true }

[dependencies]
shared = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
garde = { workspace = true }
compact_str = { workspace = true }
uuid = { workspace = true }
wings-api = { workspace = true }
axum = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
